--- 
abstract: Dist::Zilla with meta resources
author: 
  - Fayland Lam <fayland@gmail.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.006
license: perl
name: Dist-Zilla-Plugin-MetaResources
requires: 
  Dist::Zilla: 1.006
version: 0.01
